INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(1, 'Reduces acne')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(1, 'Healthy reproductive system')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(1, 'Protects eye sight')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(2, 'Helps convert food into energy')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(2, 'Healthy brain function')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(2, 'Critical for nerve function')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(3, 'Helps convert food into energy')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(3, 'Promotes healthy skin')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(4, 'Aids in lowering homocysteine levels')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(4, 'May reduce the risk of heart disease')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(4, 'Helps convert tryptophan to niacin and serotonin, a neurotransmitter that plays key roles in sleep, appetite, and moods.')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(4, 'Helps make red blood cells')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(4, 'Influences cognitive abilities and immune function')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(5, 'Assists in making new cells and breaking down some fatty acids and amino acids')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(5, 'Protects nerve cells and encourages their normal growth')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(5, 'Helps make red blood cells and DNA')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(5, 'A lack of vitamin B12 can cause memory loss, dementia, and numbness in the arms and legs')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(6, 'Helps synthesize glucose')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(7, 'May lower the risk for some cancers, including those of the mouth, esophagus, stomach, and breast')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(7, 'May protect against cataracts')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(7, 'Helps make collagen, a connective tissue that knits together wounds and supports blood vessel walls')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(7, 'Helps make the neurotransmitters serotonin and norepinephrine')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(7, 'Bolsters the immune system')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(8, 'Helps maintain normal blood levels of calcium and phosphorus, which strengthen bone')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(8, 'Helps form teeth and bones')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(8, 'Supplements can reduce the number of non-spinal fractures')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(9, 'Diets rich in vitamin E may help prevent Alzheimer''s disease')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(10, 'Vital for new cell creation')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(10, 'Helps prevent brain and spine birth defects when taken early in pregnancy')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(10, 'May reduce risk for colon cancer')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(10, 'Offsets breast cancer risk among women who consume alcohol')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(11, 'Activates proteins for normal blood clotting')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(11, 'Helps with wound healing')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(12, 'Helps with muscle contractions and relaxation')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(12, 'Builds and protects bones and teeth')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(12, 'Plays a role in hormone secretion and enzyme activation')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(12, 'Helps maintain healthy blood pressure')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(13, 'A component of stomach acid, essential to digestion')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(14, 'Enhances the activity of insulin')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(14, 'Helps maintain normal blood glucose levels')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(15, 'Plays an important role in iron metabolism and immune system')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(16, 'Encourages strong bone formation. Keeps dental cavities from starting or worsening')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(17, 'Influences nerve and muscle function, reproduction, and growth')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(18, 'Helps hemoglobin in red blood cells and myoglobin in muscle cells ferry oxygen throughout the body')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(18, 'Needed for chemical reactions in the body and for making amino acids, collagen, neurotransmitters, and hormones')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(19, 'Needed for many chemical reactions in the body')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(19, 'Works with calcium in muscle contraction, blood clotting, and regulation of blood pressure')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(20, 'Helps metabolize amino acids, cholesterol, and carbohydrates')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(21, 'Helps ward off a form of severe neurological damage in infants that can lead to early death')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(22, 'Help shuttle nutrients into and out of cells')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(23, 'Balances fluids in the body')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(23, 'Helps maintain steady heartbeat and send nerve impulses')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(23, 'Needed for muscle contractions')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(23, 'A diet rich in potassium seems to lower blood pressure')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(24, 'Acts as an antioxidant, neutralizing unstable molecules that can damage cells')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(24, 'Helps regulate thyroid hormone activity')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(25, 'Helps send nerve impulses')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(25, 'Needed for muscle contractions')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(25, 'Impacts blood pressure')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(26, 'Helps form bridges that shape and stabilize some protein structures')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(26, 'Needed for healthy hair, skin, and nails')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(27, 'Helps form many enzymes and proteins and create new cells')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(27, 'Frees vitamin A from storage in the liver')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(27, 'Needed for immune system, taste, smell, and wound healing')
INSERT INTO VitaminDB..Benefit (VitaminID, Benefit) VALUES(27, 'When taken with certain antioxidants, zinc may delay the progression of age-related macular degeneration')
